name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-docs:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout V
        uses: actions/checkout@v2
        with:
          repository: vlang/v
      - uses: actions/checkout@v2
        with:
          path: crdt
      - name: Build local V
          run: make
      - name: Run tests
          run: v test .
